Headerand first section
fpsapc/MicroverseStudentProject1 pull request #1
Opened 2023-02-16 15:57 UTC by fpsapc

add linters, add index.html, add styles.css, add necessary html, add styling, add img folder, add readme

2023-02-16 16:59 UTC, Zuhaib042 reviewed
Hi @fpsapc , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional readme.
Kindly remove all these kind of lines `Describe your project in 1 or 2 sentences.` from your readme and fill all the sections with appropriate and relevant information about your project.  for example write the description of your project and how to get started and key features and future features and remove the section that is not relevant for example server and database in tech stack and live demo section if you don't one now.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-16 17:52 UTC, fpsapc commented
> Hi @fpsapc ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that doesn't have a professional readme. Kindly remove all these kind of lines `Describe your project in 1 or 2 sentences.` from your readme and fill all the sections with appropriate and relevant information about your project. for example write the description of your project and how to get started and key features and future features and remove the section that is not relevant for example server and database in tech stack and live demo section if you don't one now.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

@Zuhaib042 I have made changes in my readme file as you suggested please check it now. Thanks

2023-02-16 19:22 UTC, fpsapc commented
Dear sir, I have submitted again please check it. Thank you

On Thu, Feb 16, 2023, 9:59 PM Zuhaib Amjad ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Hi @fpsapc <https://github.com/fpsapc> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
> You have submitted a project, that doesn't have a professional readme.
> Kindly remove all these kind of lines Describe your project in 1 or 2
> sentences. from your readme and fill all the sections with appropriate
> and relevant information about your project. for example write the
> description of your project and how to get started and key features and
> future features and remove the section that is not relevant for example
> server and database in tech stack and live demo section if you don't one
> now.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fpsapc/MicroverseStudentProject1/pull/1#pullrequestreview-1301910141>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A25DVLLWXPGLARBGB6ARLNTWXZMIPANCNFSM6AAAAAAU6LLARQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-16 19:37 UTC, shella12 requested changes

2023-02-16 19:37 UTC, shella12 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [x] Good job adding a link to the MIT Licence into your README, but please remove _`Note:`_ from the LICENCE section of the README. Note is there in the template to guide you on how to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it

2023-02-16 19:37 UTC, shella12 commented on README.md
> +- [👥 Authors](#Salman Ahmad Khan)
- [x] Please 🙏 fix the links to Authors and Built with sections in the content table

2023-02-16 19:37 UTC, shella12 commented on index.html
> +        <nav class="logo">My Logo</nav>
- [x] Please use `<a>` tag for the logo and put a link to your home page, so upon clicking logo, the user is navigated to the `Home` page. This is for three reasons: convention, semantics, and user experience(UX). It also has the added benefit of being more accessible (especially if you use an alt attribute on your logo), which makes search engine bots happier. That said, I would not use an `<h1>` tag for a logo since the heading tags should structure your HTML.

2023-02-16 19:37 UTC, shella12 commented on index.html
> +        <div><i class="fa-sharp fa-solid fa-bars"></i></div>
- [x] Please ☺️ use appropriate semantic tags 🏷️ for the header. I suggest putting the hamburger 🍔 `icon` inside the  `nav` tag along with the logo. Hamburger is part of the navigation since the hamburger icon is going to contain future nav links 😉 😃  . 

> The nav element represents a section of a page that links to other pages or to parts within the page: a section with navigation links. Not all groups of links on a page need to be in a nav element — the element is primarily intended for sections that consist of major navigation blocks.

2023-02-16 19:37 UTC, shella12 commented on styles/styles.css
> +}
- [ ] Please import `Roboto` from [Google fonts](https://fonts.google.com/?query=roboto). Please make sure your fonts match with [Figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=rTgMr8v8dtgLyJg0-0)
- [ ] Also please make sure that you are using the correct font-size of the logo. 

_Note: Using fonts mentioned in the [Figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=rTgMr8v8dtgLyJg0-0) is not necessary as sometimes Figma dimensions and real world dimensions are different, you have to increase the size to make sure your project looks almost identical to figma template_

**_Your design_**

<img width="270" alt="Screenshot 2023-02-17 at 12 07 18 AM" src="https://user-images.githubusercontent.com/44798044/219463792-6e4cddd5-4af6-495a-a4b5-3cde107ce507.png">

**_Figma Design_**

<img width="382" alt="Screenshot 2023-02-17 at 12 07 09 AM" src="https://user-images.githubusercontent.com/44798044/219463869-36971067-66e4-4e46-ba6f-2f3788b845fa.png">

2023-02-16 19:37 UTC, shella12 commented on styles/styles.css
> +  font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
- [ ] Please 🙏 stick to the design template as much as possible. Make sure you use appropriate margins and padding to make your page look identical to the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471&t=tG1jh7hS4l814OsZ-0)[requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md)

**_Your design_**

<img width="276" alt="Screenshot 2023-02-17 at 12 20 59 AM" src="https://user-images.githubusercontent.com/44798044/219468291-a3d079ef-cbb7-4a28-9d65-a55d907430ad.png">

_**Figma design:**_

<img width="383" alt="Screenshot 2023-02-16 at 11 31 35 PM" src="https://user-images.githubusercontent.com/44798044/219466322-4c402cc2-c084-4521-9fd6-a8cf74440db0.png">

2023-02-16 19:37 UTC, shella12 commented on index.html
> +        </div>
- [ ] I suggest using the `ul` list tag for the social media links and wrapping each of the `<a>` tags inside `<li>` list tags. Use of appropriate sematic tags is important for the purpose of acccessibility.

2023-02-16 19:38 UTC, shella12 requested changes
Hi @fpsapc , 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Correct use of git flow ✅ 
- Good commit history ✅ 
- Descriptive pull request ✅ 

## Required Changes ♻️

- [x] _Check the comments above the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 23:30 UTC, Gambit142 requested changes
Hi @fpsapc 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- It has the header section ✔️ 
- It has the top section ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 23:30 UTC, Gambit142 commented on index.html
> +      </nav>
- [ ] The former reviewer requested that you wrap the `nav` tag around the _**hamburger**_ icon but you have wrapped it around the _**logo**_ and the _**hamburger**_ icon. Could you wrap it around the _**hamburger**_ button only? The `nav` tag should contain navigational links to other parts of the website or other sites. 👍 In the end, you should have something like this:

```HTML
<header>
  <a class="logo" href="#home">My Logo</a>
  <nav>
    <i class="fa-sharp fa-solid fa-bars"></i>
  </nav>
</header>
```

2023-02-16 23:30 UTC, Gambit142 commented on styles/styles.css
> +}
- [ ] Kindly remove all commented-out codes. Removing commented-out codes makes your work look very clean and professional. 👍 💻

2023-02-16 23:30 UTC, Gambit142 commented on index.html
> +        </div>
- [ ] I would like to reiterate what the first reviewer highlighted. When listing items on a webpage, it is semantic to use `ul` and `li` tags or `ol` and `li` tags if you want the items ordered. During the listing, kindly wrap the img tags in a tags. So the structure would be like this:

```HTML
<ul>
  <li>
    <a href="mailto:user@eample.com"> <img class="social" src="/img/Disabled.png" alt="" /></a>
  </li>
  <li>
    <a href="https://github.com/username"><img class="social" src="/img/Enabled.png" alt="" /></a>
  </li>
  ...
</ul>
```

2023-02-17 08:09 UTC, fpsapc commented
@Gambit142 please look into the changes you ask me to do. Is it fine enough or I have to do something better. Please suggest me, I have only one review behind and I don't want to repeat the week so please reply me. Thank You.

2023-02-17 13:51 UTC, Gambit142 commented
> @Gambit142 please look into the changes you ask me to do. Is it fine enough or I have to do something better. Please suggest me, I have only one review behind and I don't want to repeat the week so please reply me. Thank You.

Hi @fpsapc, great work. I can see you have implemented all the changes. Kindly request for a review through your dashboard

2023-02-17 14:10 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @fpsapc ,

I am Favour 👩🏽 , your reviewer for this PR.

Great job implementing all the required changes by the previous reviewers. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 14:17 UTC, merged